### ISSUE TITLE
Cloudformation script failing

### ISSUE THREAD

**Issue by corroded** [bitwalker/distillery-aws-example#12]
I am trying to follow the guide and encountered a problem with Cloudformation just failing to build:

![image](https://user-images.githubusercontent.com/46548/54009089-65cebb80-41a4-11e9-845c-a4f8ef95b5e4.png)

Not sure why it says it already exists when this AWS is almost new. I only have 5 folders in S3 and none of them are for distillery. Am I missing something crucial here? This is the latest branch btw (since I already encountered the problems in #5 (the Github token, specifically).

**Comment by bitwalker** [comment]
In the guide in the Distillery docs, it calls out the fact that in AWS, S3 bucket names must be _globally_ unique, by which I mean, every S3 bucket in the world has to have a unique name, regardless of what account they are under. The typical solution to this is to provide a prefix that is unique to your org, or to generate a random name. The error you are getting is because that bucket has already been created somewhere else.

I'm not sure why AWS chose to require S3 buckets be globally unique, rather than unique within an account, it is really stupid, but it is a hard restriction of the platform :(

**Comment by corroded** [comment]
Oh! So that's what it meant! I am sorry, I misunderstood. When the docs said "globally" unique I thought it meant it was unique across all availability zones in our organization - not across the whole everyone elses. My bad!

Thanks for clearing that up! 💯

**Comment by bitwalker** [comment]
No worries :)
